spring:
  application:
    name: security
  config:
    import: "optional:configserver:http://localhost:8888/"

management:
  endpoints:
    jmx:
      exposure:
        include: "beans,health,mappings"

