eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8161/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
server:
  port: ${PORT:8080}

logging:
  level:
    root: DEBUG
