spring:
  application:
    name: registy
  config:
    import: "optional:configserver:http://localhost:8888/"

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

